'use client';

import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import TemplateEditor,{TemplateRegions} from './TemplateEditor';

type Photo={id:string;file:File;url:string};
type Transform={scale:number;x:number;y:number};
type OrderStatus='pending'|'ready';
type Order={id:string;name:string;cover:Photo;preview?:Photo;photos:Photo[];arrangement:Photo[];transforms:Record<string,Transform>;status:OrderStatus};
type TemplateRecord={id:string;name:string;file:File};
type Filter='all'|OrderStatus;

const months=['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'];
const initialTransform:Transform={scale:1,x:0,y:0};
const defaultRegions:TemplateRegions={cover:{x:4.4,y:3.1,width:91.2,height:61.4,curve:0},inner:{x:4.4,y:3.1,width:91.2,height:50.5,curve:-8}};

function shuffle<T>(items:T[]){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
function arrange(photos:Photo[]){if(!photos.length)return[];const result:Photo[]=[];let previous='';while(result.length<12){let round=shuffle(photos);if(round.length>1&&round[0].id===previous)[round[0],round[1]]=[round[1],round[0]];round=round.slice(0,12-result.length);result.push(...round);previous=result.at(-1)?.id??'';}return result;}
function arrangeInSequence(photos:Photo[]){const fixed=photos.slice(0,12);return[...fixed,...arrange(photos).slice(0,12-fixed.length)];}
function safeName(value:string){return value.replace(/[\\/:*?"<>|]/g,'-').trim();}
function regionClip(region:TemplateRegions['inner']){const edge=region.curve>=0?100-region.curve:100,center=region.curve>=0?100:100+region.curve;return`polygon(0 0,100% 0,100% ${edge}%,75% ${(edge+center)/2}%,50% ${center}%,25% ${(edge+center)/2}%,0 ${edge}%)`;}
function sequenceOf(name:string){const match=name.match(/消费者上传原图[^\d]*(\d+)(?=[^\d]*\.[^.]+$)/);return match?Number(match[1]):null;}
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('calendar-workshop',2);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('files'))db.createObjectStore('files');if(!db.objectStoreNames.contains('templates'))db.createObjectStore('templates');};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function saveTemplates(files:File[]){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction('templates','readwrite'),store=tx.objectStore('templates');files.forEach(file=>store.put({name:file.name,type:file.type,blob:file},file.name));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}
async function loadTemplates(){const db=await openDb();let records=await new Promise<Array<{name:string;type:string;blob:Blob}>>((resolve,reject)=>{const request=db.transaction('templates').objectStore('templates').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});if(!records.length&&db.objectStoreNames.contains('files')){const legacy=await new Promise<{name:string;type:string;blob:Blob}|undefined>((resolve,reject)=>{const request=db.transaction('files').objectStore('files').get('template');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});if(legacy){records=[legacy];await new Promise<void>((resolve,reject)=>{const tx=db.transaction('templates','readwrite');tx.objectStore('templates').put(legacy,legacy.name);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}}db.close();return records.map(record=>({id:record.name,name:record.name,file:new File([record.blob],record.name,{type:record.type})}));}
async function optimizedJpeg(file:File,width:number,height:number,transform:Transform){const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'}),canvas=document.createElement('canvas');canvas.width=Math.round(width);canvas.height=Math.round(height);const context=canvas.getContext('2d',{alpha:false});if(!context)throw new Error('无法处理图片');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);const baseScale=Math.max(canvas.width/bitmap.width,canvas.height/bitmap.height),w=bitmap.width*baseScale*transform.scale,h=bitmap.height*baseScale*transform.scale,x=(canvas.width-w)/2+canvas.width*transform.x/100,y=(canvas.height-h)/2+canvas.height*transform.y/100;context.drawImage(bitmap,x,y,w,h);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('图片压缩失败')),'image/jpeg',.9));return new Uint8Array(await blob.arrayBuffer());}

export default function Home(){
  const [templates,setTemplates]=useState<TemplateRecord[]>([]),[selectedTemplateId,setSelectedTemplateId]=useState(''),[templatePages,setTemplatePages]=useState<string[]>([]),[regions,setRegions]=useState<TemplateRegions>(defaultRegions),[editingTemplate,setEditingTemplate]=useState(false),[orders,setOrders]=useState<Order[]>([]),[selectedId,setSelectedId]=useState(''),[selectedPage,setSelectedPage]=useState(0),[search,setSearch]=useState(''),[filter,setFilter]=useState<Filter>('all'),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[message,setMessage]=useState('请选择批量订单文件夹');const urls=useRef<string[]>([]);
  const template=templates.find(item=>item.id===selectedTemplateId)?.file??null;
  const selectedOrder=orders.find(order=>order.id===selectedId)??orders[0];
  const selectedPhoto=selectedOrder?(selectedPage===0?selectedOrder.cover:selectedOrder.arrangement[selectedPage-1]):undefined;
  const selectedTransform=selectedPhoto&&selectedOrder?selectedOrder.transforms[selectedPhoto.id]??initialTransform:initialTransform;
  const templateBase=template?safeName(template.name.replace(/\.pdf$/i,'')):'template';
  const readyCount=orders.filter(order=>order.status==='ready').length,pendingCount=orders.length-readyCount;
  const visibleOrders=useMemo(()=>orders.filter(order=>(filter==='all'||order.status===filter)&&order.name.toLowerCase().includes(search.toLowerCase())),[orders,filter,search]);

  useEffect(()=>{loadTemplates().then(items=>{setTemplates(items);setSelectedTemplateId(items[0]?.id??'');}).catch(()=>{});return()=>urls.current.forEach(URL.revokeObjectURL);},[]);
  useEffect(()=>{if(!selectedTemplateId)return;try{setRegions(JSON.parse(localStorage.getItem(`jht-template-region:${selectedTemplateId}`)??'null')??defaultRegions);}catch{setRegions(defaultRegions);}},[selectedTemplateId]);
  useEffect(()=>{if(!template){setTemplatePages([]);return;}let cancelled=false;(async()=>{try{const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc=pdfWorkerUrl;const pdfDocument=await pdfjs.getDocument({data:new Uint8Array(await template.arrayBuffer())}).promise;if(pdfDocument.numPages!==13)throw new Error('模板必须是13页');const pages:string[]=[];for(let i=1;i<=13;i++){const page=await pdfDocument.getPage(i),viewport=page.getViewport({scale:.55}),canvas=document.createElement('canvas'),context=canvas.getContext('2d');canvas.width=viewport.width;canvas.height=viewport.height;if(context)await page.render({canvas,canvasContext:context,viewport}).promise;pages.push(canvas.toDataURL('image/jpeg',.8));}if(!cancelled){setTemplatePages(pages);setMessage('模板已就绪');}}catch(error){if(!cancelled)setMessage(error instanceof Error?error.message:'模板预览失败');}})();return()=>{cancelled=true};},[template]);

  const addPhoto=(file:File):Photo=>{const url=URL.createObjectURL(file);urls.current.push(url);return{id:`${file.webkitRelativePath||file.name}-${file.size}-${crypto.randomUUID()}`,file,url};};
  const importFolder=(event:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files??[]).filter(file=>file.type.startsWith('image/')||/\.(jpe?g|png|webp|heic)$/i.test(file.name)),groups=new Map<string,File[]>();for(const file of files){const parts=file.webkitRelativePath.split('/').filter(Boolean),name=parts.length>=3?parts[1]:parts[0]||'未命名订单';groups.set(name,[...(groups.get(name)??[]),file]);}let skipped=0;const next:Order[]=[...groups.entries()].sort(([a],[b])=>a.localeCompare(b,'zh-CN')).flatMap(([name,groupFiles])=>{const numbered=groupFiles.map(file=>({file,sequence:sequenceOf(file.name)})).filter((item):item is {file:File;sequence:number}=>item.sequence!==null).sort((a,b)=>a.sequence-b.sequence||a.file.name.localeCompare(b.file.name,'zh-CN')),coverFile=numbered.find(item=>item.sequence===1)?.file,insideFiles=numbered.filter(item=>item.sequence!==1).map(item=>item.file),previewFile=groupFiles.find(file=>/合成预览图/.test(file.name));if(!coverFile||!insideFiles.length){skipped++;return[];}const cover=addPhoto(coverFile),preview=previewFile?addPhoto(previewFile):undefined,photos=insideFiles.map(addPhoto),transforms:Record<string,Transform>={[cover.id]:initialTransform};photos.forEach(photo=>transforms[photo.id]=initialTransform);return[{id:crypto.randomUUID(),name,cover,preview,photos,arrangement:arrangeInSequence(photos),transforms,status:'pending'}];});setOrders(next);setSelectedId(next[0]?.id??'');setSelectedPage(0);setMessage(next.length?`已读取 ${next.length} 个订单${skipped?`，跳过 ${skipped} 个缺少有效图片的文件夹`:''}`:'没有找到符合“消费者上传原图+序号”的订单');event.target.value='';};
  const chooseTemplates=async(event:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files??[]).filter(file=>/\.pdf$/i.test(file.name));if(!files.length)return;await saveTemplates(files);const next=await loadTemplates();setTemplates(next);setSelectedTemplateId(files[0].name);setMessage(`模板列表已加入 ${files.length} 个文件`);event.target.value='';};
  const updateOrder=(id:string,updater:(order:Order)=>Order)=>setOrders(current=>current.map(order=>order.id===id?updater(order):order));
  const updateTransform=(patch:Partial<Transform>)=>{if(!selectedOrder||!selectedPhoto)return;updateOrder(selectedOrder.id,order=>({...order,transforms:{...order.transforms,[selectedPhoto.id]:{...(order.transforms[selectedPhoto.id]??initialTransform),...patch}},status:'pending'}));};
  const resetTransform=()=>updateTransform(initialTransform);
  const movePage=(index:number,direction:-1|1)=>{if(!selectedOrder)return;const target=index+direction;if(target<0||target>11)return;updateOrder(selectedOrder.id,order=>{const next=[...order.arrangement];[next[index],next[target]]=[next[target],next[index]];return{...order,arrangement:next,status:'pending'};});setSelectedPage(target+1);};
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(!selectedPhoto||['INPUT','TEXTAREA'].includes((event.target as HTMLElement)?.tagName))return;const step=event.shiftKey?5:1;if(event.key==='ArrowLeft'){event.preventDefault();updateTransform({x:selectedTransform.x-step});}else if(event.key==='ArrowRight'){event.preventDefault();updateTransform({x:selectedTransform.x+step});}else if(event.key==='ArrowUp'){event.preventDefault();updateTransform({y:selectedTransform.y-step});}else if(event.key==='ArrowDown'){event.preventDefault();updateTransform({y:selectedTransform.y+step});}else if(event.key==='+'||event.key==='='){event.preventDefault();updateTransform({scale:Math.min(3,selectedTransform.scale+.05)});}else if(event.key==='-'){event.preventDefault();updateTransform({scale:Math.max(1,selectedTransform.scale-.05)});}else if(event.key==='0'){event.preventDefault();resetTransform();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[selectedPhoto,selectedTransform,selectedOrder]);

  const buildPdf=async(order:Order)=>{if(!template)throw new Error('请先选择模板');const pdf=await import('pdf-lib'),output=await pdf.PDFDocument.load(await template.arrayBuffer());if(output.getPageCount()!==13)throw new Error('模板必须是13页');const pageWidth=595.276,pageHeight=841.89,toPdf=(region:TemplateRegions['cover'])=>({x:pageWidth*region.x/100,y:pageHeight*(100-region.y-region.height)/100,width:pageWidth*region.width/100,height:pageHeight*region.height/100}),coverBox=toPdf(regions.cover),coverImage=await output.embedJpg(await optimizedJpeg(order.cover.file,Math.round(2480*regions.cover.width/100),Math.round(3508*regions.cover.height/100),order.transforms[order.cover.id]??initialTransform)),coverPage=output.getPage(0);coverPage.drawImage(coverImage,coverBox);coverPage.drawRectangle({...coverBox,borderColor:pdf.rgb(1,1,1),borderWidth:2.5});for(let index=0;index<12;index++){const page=output.getPage(index+1),photo=order.arrangement[index],box=toPdf(regions.inner),curveHeight=box.height*Math.abs(regions.inner.curve)/100,edgeY=regions.inner.curve>=0?box.y+curveHeight:box.y,centerY=regions.inner.curve>=0?box.y:box.y+curveHeight,image=await output.embedJpg(await optimizedJpeg(photo.file,Math.round(2480*regions.inner.width/100),Math.round(3508*regions.inner.height/100),order.transforms[photo.id]??initialTransform));page.pushOperators(pdf.pushGraphicsState(),pdf.moveTo(box.x,box.y+box.height),pdf.lineTo(box.x,edgeY),pdf.appendBezierCurve(box.x+box.width*.2,edgeY,box.x+box.width*.3,centerY,box.x+box.width*.5,centerY),pdf.appendBezierCurve(box.x+box.width*.7,centerY,box.x+box.width*.8,edgeY,box.x+box.width,edgeY),pdf.lineTo(box.x+box.width,box.y+box.height),pdf.lineTo(box.x,box.y+box.height),pdf.clip(),pdf.endPath());page.drawImage(image,box);page.pushOperators(pdf.popGraphicsState());page.drawLine({start:{x:box.x,y:box.y+box.height},end:{x:box.x,y:edgeY},color:pdf.rgb(1,1,1),thickness:2.5});page.drawSvgPath(`M ${box.x} ${edgeY} C ${box.x+box.width*.2} ${edgeY}, ${box.x+box.width*.3} ${centerY}, ${box.x+box.width*.5} ${centerY} C ${box.x+box.width*.7} ${centerY}, ${box.x+box.width*.8} ${edgeY}, ${box.x+box.width} ${edgeY}`,{borderColor:pdf.rgb(1,1,1),borderWidth:2.5});page.drawLine({start:{x:box.x+box.width,y:edgeY},end:{x:box.x+box.width,y:box.y+box.height},color:pdf.rgb(1,1,1),thickness:2.5});page.drawLine({start:{x:box.x+box.width,y:box.y+box.height},end:{x:box.x,y:box.y+box.height},color:pdf.rgb(1,1,1),thickness:2.5});}const name=`${templateBase}-${safeName(order.name)}`;output.setTitle(name);output.setCreator('JHT ISP SYSTEM');return{name,bytes:await output.save({useObjectStreams:true,addDefaultPage:false})};
  };
  const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const exportCurrent=async()=>{if(!selectedOrder)return;setBusy(true);try{setProgress(`正在导出 ${selectedOrder.name}`);const result=await buildPdf(selectedOrder);download(new Blob([result.bytes as BlobPart],{type:'application/pdf'}),`${result.name}.pdf`);setMessage(`${selectedOrder.name} 导出完成`);}catch(error){setMessage(error instanceof Error?error.message:'导出失败');}finally{setBusy(false);setProgress('');}};
  const exportAll=async()=>{const targets=orders.filter(order=>order.status==='ready');if(!targets.length)return;setBusy(true);try{const JSZip=(await import('jszip')).default,zip=new JSZip();for(let i=0;i<targets.length;i++){setProgress(`正在生成 ${i+1}/${targets.length}：${targets[i].name}`);const result=await buildPdf(targets[i]);zip.file(`${result.name}.pdf`,result.bytes);}setProgress('正在打包…');download(await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),`${templateBase}-已排版-${targets.length}个订单.zip`);setMessage(`已打包导出 ${targets.length} 个订单`);}catch(error){setMessage(error instanceof Error?error.message:'批量导出失败');}finally{setBusy(false);setProgress('');}};

  const pages=selectedOrder?[{label:'封面',photo:selectedOrder.cover},...months.map((label,index)=>({label,photo:selectedOrder.arrangement[index]}))]:[];
  return <main className="app-shell"><header className="system-bar"><div className="system-name"><span>JHT</span><b>ISP SYSTEM</b></div><div className="header-actions"><button className="header-button secondary" disabled={!templatePages.length} onClick={()=>setEditingTemplate(true)}>绘制定制区域</button><label className="header-button secondary">添加模板<input type="file" accept="application/pdf" multiple onChange={chooseTemplates}/></label><label className="header-button primary">导入订单文件夹<input type="file" accept="image/*" webkitdirectory="" directory="" multiple onChange={importFolder}/></label></div></header>
    <div className="summary-bar"><div className="template-picker"><span>模板</span><select value={selectedTemplateId} onChange={event=>setSelectedTemplateId(event.target.value)}><option value="">请选择模板</option>{templates.map(item=><option value={item.id} key={item.id}>{item.name.replace(/\.pdf$/i,'')}</option>)}</select></div><div className="summary-stats"><span>订单 <b>{orders.length}</b></span><span>待排版 <b>{pendingCount}</b></span><span className="ready-text">已排版 <b>{readyCount}</b></span></div><div className="current-order">当前订单 <b>{selectedOrder?.name??'—'}</b></div></div>
    <div className="batch-workspace"><aside className="orders-panel"><div className="orders-head"><h2>订单列表</h2><span>{visibleOrders.length}/{orders.length}</span></div><input className="search" placeholder="搜索订单名称" value={search} onChange={event=>setSearch(event.target.value)}/><div className="filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>全部</button><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>未排</button><button className={filter==='ready'?'active':''} onClick={()=>setFilter('ready')}>已排</button></div><div className="order-list">{visibleOrders.map((order,index)=><button className={`order-row ${selectedOrder?.id===order.id?'selected':''}`} key={order.id} onClick={()=>{setSelectedId(order.id);setSelectedPage(0)}}><span className={`status-mark ${order.status}`}>{order.status==='ready'?'✓':String(index+1).padStart(2,'0')}</span><span><b>{order.name}</b><small>{order.photos.length+1} 张图片</small></span><em>{order.status==='ready'?'已排版':'待排版'}</em></button>)}{!visibleOrders.length&&<p className="empty-list">没有匹配订单</p>}</div></aside>
      <section className="pages-panel"><div className="pages-head"><div><h1>{selectedOrder?.name??'请导入订单文件夹'}</h1><p>{selectedOrder?`输出：${templateBase}-${safeName(selectedOrder.name)}.pdf`:'每个一级子文件夹将被识别为一个订单'}</p></div>{selectedOrder&&<div className="order-actions"><button onClick={()=>updateOrder(selectedOrder.id,order=>({...order,arrangement:arrange(order.photos),status:'pending'}))}>↻ 重新随机</button><button className={selectedOrder.status==='ready'?'confirmed':''} onClick={()=>updateOrder(selectedOrder.id,order=>({...order,status:order.status==='ready'?'pending':'ready'}))}>{selectedOrder.status==='ready'?'✓ 已排版':'确认已排版'}</button></div>}</div>
        {selectedOrder?<div className="page-grid">{pages.map((item,index)=>{const transform=selectedOrder.transforms[item.photo.id]??initialTransform,region=index===0?regions.cover:regions.inner;return <article className={`page-card page-position-${index} ${selectedPage===index?'selected':''}`} key={`${item.label}-${index}`} onClick={()=>setSelectedPage(index)}><div className="a4-page">{templatePages[index]?<img className="template-page" src={templatePages[index]} alt={`${item.label}模板`}/>:<div className="page-loading">模板加载中</div>}<div className="custom-photo" style={{left:`${region.x}%`,top:`${region.y}%`,width:`${region.width}%`,height:`${region.height}%`,clipPath:index===0?'none':regionClip(regions.inner)}}><img src={item.photo.url} alt={item.photo.file.name} style={{transform:`translate(${transform.x}%,${transform.y}%) scale(${transform.scale})`}}/></div>{selectedPage===index&&<span className="editing-badge">正在调整</span>}<span className="page-index">{String(index+1).padStart(2,'0')}</span></div><div className="page-caption"><span><b>{item.label}</b><small>{item.photo.file.name}</small></span>{index>0&&<div className="move-buttons"><button disabled={index===1} onClick={event=>{event.stopPropagation();movePage(index-1,-1)}}>←</button><button disabled={index===12} onClick={event=>{event.stopPropagation();movePage(index-1,1)}}>→</button></div>}</div></article>})}</div>:<div className="empty-stage"><b>从文件夹开始</b><p>选择一个包含多个订单子文件夹的总文件夹。</p></div>}
      </section>
      <aside className={`adjust-panel ${selectedPhoto?'active':''}`}><div className="adjust-title"><span>03</span><div><h2>图片调整</h2><p>{selectedPhoto?.file.name??'先选择一个页面'}</p></div></div><div className="selected-preview">{selectedPhoto?<img src={selectedPhoto.url} alt="当前调整图片" style={{transform:`translate(${selectedTransform.x}%,${selectedTransform.y}%) scale(${selectedTransform.scale})`}}/>:<span>无图片</span>}<em>{selectedPage===0?'封面':months[selectedPage-1]}</em></div>{selectedOrder?.preview&&<div className="order-reference"><b>合成预览图</b><img src={selectedOrder.preview.url} alt="合成预览图"/><small>仅供整体效果参考，不参与导出</small></div>}<label><span>缩放 <output>{selectedTransform.scale.toFixed(2)}×</output></span><input type="range" min="1" max="3" step=".01" value={selectedTransform.scale} disabled={!selectedPhoto} onChange={event=>updateTransform({scale:Number(event.target.value)})}/></label><label><span>左右 <output>{selectedTransform.x}</output></span><input type="range" min="-50" max="50" value={selectedTransform.x} disabled={!selectedPhoto} onChange={event=>updateTransform({x:Number(event.target.value)})}/></label><label><span>上下 <output>{selectedTransform.y}</output></span><input type="range" min="-50" max="50" value={selectedTransform.y} disabled={!selectedPhoto} onChange={event=>updateTransform({y:Number(event.target.value)})}/></label><button className="reset" onClick={resetTransform} disabled={!selectedPhoto}>重置当前图片</button><div className="shortcuts"><b>键盘快捷键</b><p><kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> 移动 1%</p><p><kbd>Shift</kbd> + 方向键 移动 5%</p><p><kbd>+</kbd><kbd>-</kbd> 缩放· <kbd>0</kbd> 重置</p></div></aside>
    </div>
    <footer className="export-bar"><div><span className={`status-dot ${readyCount?'ok':''}`}/><div><b>{progress||message}</b><small>{orders.length?`已排版 ${readyCount} / ${orders.length}`:'等待导入订单'}</small></div></div><div className="export-actions"><button disabled={!selectedOrder||busy||!template} onClick={exportCurrent}>导出当前</button><button className="batch-export" disabled={!readyCount||busy||!template} onClick={exportAll}>批量导出已排版 <span>{readyCount}</span></button></div></footer>{editingTemplate&&<TemplateEditor pages={templatePages} value={regions} onClose={()=>setEditingTemplate(false)} onSave={value=>{setRegions(value);localStorage.setItem(`jht-template-region:${selectedTemplateId}`,JSON.stringify(value));setEditingTemplate(false);setMessage('模板定制区域已保存');}}/>}
  </main>;
}
