'use client';

import { ChangeEvent, MouseEvent, PointerEvent, useRef, useState } from 'react';

export type Point={x:number;y:number;inX?:number;inY?:number;outX?:number;outY?:number};
export type Region={x:number;y:number;width:number;height:number;curve:number;points?:Point[]};
export type TemplateRegions={cover:Region;inner:Region};
type PageMode='all'|'odd'|'even';
type Drag={index:number;kind:'point'|'in'|'out'};
type Props={pages:string[];value:TemplateRegions;templateName:string;hasCover:boolean;pageCount?:number;pageMode?:PageMode;duplex?:boolean;rotateImported?:boolean;rotateCover?:boolean;rotateInner?:boolean;onForegroundFile?:(file:File)=>void;onSave:(value:TemplateRegions,name:string,hasCover:boolean,pageMode:PageMode,duplex:boolean,rotateCover:boolean,rotateInner:boolean)=>void;onClose:()=>void};

const n=(value:number)=>Math.max(0,Math.min(100,value));
const handle=(point:Point,kind:'in'|'out')=>({x:point[`${kind}X`]??point.x,y:point[`${kind}Y`]??point.y});

export default function TemplateEditor({pages,value,templateName,hasCover,pageCount=pages.length,pageMode='all',duplex=false,rotateImported=false,rotateCover,rotateInner,onForegroundFile,onSave,onClose}:Props){
  const storage=typeof localStorage==='undefined'?null:localStorage,nameKey=storage?Object.keys(storage).find(key=>key.startsWith('jht-template-name:')&&storage.getItem(key)===templateName):undefined,storageId=nameKey?.slice('jht-template-name:'.length),storedCover=storageId?storage?.getItem(`jht-template-rotate-cover:${storageId}`):null,storedInner=storageId?storage?.getItem(`jht-template-rotate-inner:${storageId}`):null,initialRotateCover=rotateCover??(storedCover===null?rotateImported:storedCover==='true'),initialRotateInner=rotateInner??(storedInner===null?rotateImported:storedInner==='true');
  const [mode,setMode]=useState<'cover'|'inner'>(hasCover?'cover':'inner'),[regions,setRegions]=useState(value),[zoom,setZoom]=useState(1.15),[selected,setSelected]=useState(0),[name,setName]=useState(templateName),[draftHasCover,setDraftHasCover]=useState(hasCover),[draftPageMode,setDraftPageMode]=useState<PageMode>(pageMode),[draftDuplex,setDraftDuplex]=useState(duplex),[draftRotateCover,setDraftRotateCover]=useState(initialRotateCover),[draftRotateInner,setDraftRotateInner]=useState(initialRotateInner);
  const stage=useRef<HTMLDivElement>(null),drag=useRef<Drag|null>(null),region=regions[mode],points=region.points??[];
  const innerPageIndex=Array.from({length:pageCount},(_,index)=>index+1).find(page=>(!draftHasCover||page!==1)&&(draftPageMode==='all'||(draftPageMode==='odd'?page%2===1:page%2===0)))??1;
  const previewPageIndex=mode==='cover'?0:innerPageIndex-1;
  const setPoints=(next:Point[])=>setRegions(current=>({...current,[mode]:{...current[mode],points:next}}));
  const locate=(clientX:number,clientY:number)=>{const rect=stage.current!.getBoundingClientRect();return{x:n((clientX-rect.left)/rect.width*100),y:n((clientY-rect.top)/rect.height*100)};};
  const addPoint=(event:MouseEvent<HTMLDivElement>)=>{if((event.target as Element).closest('svg'))return;const point=locate(event.clientX,event.clientY);setPoints([...points,point]);setSelected(points.length);};
  const beginDrag=(event:PointerEvent,entry:Drag)=>{event.stopPropagation();drag.current=entry;(event.currentTarget as Element).setPointerCapture(event.pointerId);setSelected(entry.index);};
  const moveDrag=(event:PointerEvent)=>{if(!drag.current)return;const next=[...points],position=locate(event.clientX,event.clientY),{index,kind}=drag.current,point={...next[index]};if(kind==='point'){const dx=position.x-point.x,dy=position.y-point.y;point.x=position.x;point.y=position.y;if(point.inX!==undefined){point.inX=n(point.inX+dx);point.inY=n((point.inY??point.y)+dy);}if(point.outX!==undefined){point.outX=n(point.outX+dx);point.outY=n((point.outY??point.y)+dy);}}else{point[`${kind}X`]=position.x;point[`${kind}Y`]=position.y;}next[index]=point;setPoints(next);};
  const updatePoint=(index:number,patch:Partial<Point>)=>{const next=[...points];next[index]={...next[index],...patch};setPoints(next);};
  const enableCurve=(index:number)=>{const next=[...points],point=next[index],previous=next[(index-1+next.length)%next.length]??point,following=next[(index+1)%next.length]??point,dx=(following.x-previous.x)*.16,dy=(following.y-previous.y)*.16;next[index]={...point,inX:n(point.x-dx),inY:n(point.y-dy),outX:n(point.x+dx),outY:n(point.y+dy)};setPoints(next);};
  const transformOutline=(scale:number,dx=0,dy=0)=>{if(!points.length)return;const cx=points.reduce((sum,point)=>sum+point.x,0)/points.length,cy=points.reduce((sum,point)=>sum+point.y,0)/points.length,adjust=(x:number,y:number)=>({x:n(cx+(x-cx)*scale+dx),y:n(cy+(y-cy)*scale+dy)});setPoints(points.map(point=>{const position=adjust(point.x,point.y),incoming=adjust(point.inX??point.x,point.inY??point.y),outgoing=adjust(point.outX??point.x,point.outY??point.y);return{...point,...position,...(point.inX===undefined?{}:{inX:incoming.x,inY:incoming.y}),...(point.outX===undefined?{}:{outX:outgoing.x,outY:outgoing.y})};}));};
  const importSvg=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const documentNode=new DOMParser().parseFromString(await file.text(),'image/svg+xml'),source=documentNode.documentElement;if(source.tagName.toLowerCase()!=='svg'||documentNode.querySelector('parsererror'))throw new Error('SVG格式无效');const viewBox=(source.getAttribute('viewBox')??`0 0 ${source.getAttribute('width')??100} ${source.getAttribute('height')??100}`).trim().split(/[ ,]+/).map(Number),[vx,vy,vw,vh]=viewBox.length===4&&viewBox.every(Number.isFinite)&&viewBox[2]>0&&viewBox[3]>0?viewBox:[0,0,100,100],host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:-10000px;width:1000px;height:1000px;visibility:hidden';host.innerHTML=new XMLSerializer().serializeToString(source);document.body.appendChild(host);const svg=host.querySelector('svg')!,paths=Array.from(svg.querySelectorAll('path')).filter(path=>{try{return path.getTotalLength()>0}catch{return false}}),path=paths.sort((a,b)=>b.getTotalLength()-a.getTotalLength())[0];let raw:Array<{x:number;y:number}>=[];if(path){const length=path.getTotalLength(),samples=Math.max(24,Math.min(96,Math.ceil(length/12))),pathMatrix=path.getCTM(),rootMatrix=svg.getCTM(),matrix=pathMatrix&&rootMatrix?rootMatrix.inverse().multiply(pathMatrix):null;raw=Array.from({length:samples},(_,index)=>{const point=path.getPointAtLength(length*index/samples),mapped=matrix?new DOMPoint(point.x,point.y).matrixTransform(matrix):point;return{x:mapped.x,y:mapped.y};});}else{const polygon=svg.querySelector('polygon,polyline');if(polygon)raw=(polygon.getAttribute('points')??'').trim().split(/\s+/).map(pair=>pair.split(',').map(Number)).filter(pair=>pair.length===2&&pair.every(Number.isFinite)).map(([x,y])=>({x,y}));}host.remove();if(raw.length<3)throw new Error('SVG中没有可用的闭合路径');setPoints(raw.map(point=>({x:n((point.x-vx)/vw*100),y:n((point.y-vy)/vh*100)})));setSelected(0);}catch(error){window.alert(error instanceof Error?error.message:'SVG轮廓导入失败');}};
  const path=points.length?`${points.map((point,index)=>{if(!index)return`M ${point.x} ${point.y}`;const previous=points[index-1],out=handle(previous,'out'),inside=handle(point,'in');return`C ${out.x} ${out.y} ${inside.x} ${inside.y} ${point.x} ${point.y}`;}).join(' ')}${points.length>2?(()=>{const last=points.at(-1)!,first=points[0],out=handle(last,'out'),inside=handle(first,'in');return` C ${out.x} ${out.y} ${inside.x} ${inside.y} ${first.x} ${first.y} Z`;})():''}`:'';
  return <div className="editor-backdrop"><section className="template-editor pro-editor">
    <header><div><b>定制模板绘制</b><span>当前模板：{templateName}</span></div><button onClick={onClose}>×</button></header>
    <div className="editor-toolbar"><div className="editor-tabs">{draftHasCover&&<button className={mode==='cover'?'active':''} onClick={()=>{setMode('cover');setSelected(0)}}>封面区域</button>}<button className={mode==='inner'?'active':''} onClick={()=>{setMode('inner');setSelected(0)}}>内页区域</button></div><label className="template-name-field">模板名称 <input value={name} onChange={event=>setName(event.target.value)}/></label><label>封面 <select value={draftHasCover?'yes':'no'} onChange={event=>{const next=event.target.value==='yes';setDraftHasCover(next);if(!next)setMode('inner');}}><option value="yes">有封面</option><option value="no">无封面</option></select></label><label>印刷方式 <select value={draftDuplex?'duplex':'single'} onChange={event=>{const next=event.target.value==='duplex';setDraftDuplex(next);if(next&&draftPageMode==='all')setDraftPageMode('odd');}}><option value="single">单面印刷</option><option value="duplex">双面印刷</option></select></label><label>插图页面 <select value={draftPageMode} onChange={event=>setDraftPageMode(event.target.value as PageMode)}><option value="all" disabled={draftDuplex}>全部页面</option><option value="odd">仅奇数页</option><option value="even">仅偶数页</option></select></label>{draftHasCover&&<label>封面图片 <select value={draftRotateCover?'rotate':'normal'} onChange={event=>setDraftRotateCover(event.target.value==='rotate')}><option value="normal">保持方向</option><option value="rotate">旋转180°</option></select></label>}<label>内页图片 <select value={draftRotateInner?'rotate':'normal'} onChange={event=>setDraftRotateInner(event.target.value==='rotate')}><option value="normal">保持方向</option><option value="rotate">旋转180°</option></select></label><label>缩放 <input type="range" min=".7" max="1.8" step=".05" value={zoom} onChange={event=>setZoom(Number(event.target.value))}/><output>{Math.round(zoom*100)}%</output></label></div>
    <div className="svg-outline-tools"><label>导入 SVG 轮廓<input type="file" accept="image/svg+xml,.svg" onChange={importSvg}/></label><label>导入前景保护 PDF<input type="file" accept="application/pdf,.pdf" onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file){onForegroundFile?.(file);window.dispatchEvent(new CustomEvent('jht-foreground-file',{detail:file}));}}}/></label><span>整体移动</span><button disabled={!points.length} onClick={()=>transformOutline(1,-.1,0)}>←</button><button disabled={!points.length} onClick={()=>transformOutline(1,.1,0)}>→</button><button disabled={!points.length} onClick={()=>transformOutline(1,0,-.1)}>↑</button><button disabled={!points.length} onClick={()=>transformOutline(1,0,.1)}>↓</button><span>整体缩放</span><button disabled={!points.length} onClick={()=>transformOutline(.998)}>－</button><button disabled={!points.length} onClick={()=>transformOutline(1.002)}>＋</button><small>每次移动0.1%，缩放0.2%；可反复点击精确调整</small></div>
    <div className="editor-body pro-body"><div className="stage-scroll"><div className="draw-stage polygon-stage grid-stage" ref={stage} style={{height:`${720*zoom}px`}} onClick={addPoint} onPointerMove={moveDrag} onPointerUp={()=>{drag.current=null}}><img src={pages[previewPageIndex]} alt="模板页面" draggable={false}/><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d={path} className="mask-polygon"/>{points.map((point,index)=>{const incoming=handle(point,'in'),outgoing=handle(point,'out'),active=index===selected;return <g key={index}>{active&&<><line x1={point.x} y1={point.y} x2={incoming.x} y2={incoming.y} className="handle-line"/><line x1={point.x} y1={point.y} x2={outgoing.x} y2={outgoing.y} className="handle-line"/><circle cx={incoming.x} cy={incoming.y} r=".42" className="curve-handle" onPointerDown={event=>beginDrag(event,{index,kind:'in'})}/><circle cx={outgoing.x} cy={outgoing.y} r=".42" className="curve-handle" onPointerDown={event=>beginDrag(event,{index,kind:'out'})}/></>}<circle cx={point.x} cy={point.y} r=".48" className={`mask-point ${active?'active':''}`} onPointerDown={event=>beginDrag(event,{index,kind:'point'})}/><text x={point.x+.7} y={point.y-.7}>{index+1}</text></g>;})}</svg></div></div><aside className="points-panel"><div className="points-head"><b>坐标点</b><span>{points.length}</span></div><p>点击空白处增加节点；拖动绿色节点移动位置。选中节点后拖动圆形手柄调整曲率。</p><div className="point-list">{points.map((point,index)=><div className={`point-row ${selected===index?'active':''}`} key={index} onClick={()=>setSelected(index)}><b>P{index+1}</b><label>X<input type="number" min="0" max="100" step=".1" value={point.x.toFixed(1)} onChange={event=>updatePoint(index,{x:n(Number(event.target.value))})}/></label><label>Y<input type="number" min="0" max="100" step=".1" value={point.y.toFixed(1)} onChange={event=>updatePoint(index,{y:n(Number(event.target.value))})}/></label><button onClick={event=>{event.stopPropagation();setPoints(points.filter((_,item)=>item!==index));setSelected(Math.max(0,index-1));}}>×</button></div>)}</div><div className="point-actions"><button disabled={!points.length} onClick={()=>enableCurve(selected)}>添加曲率手柄</button><button disabled={!points.length} onClick={()=>{setPoints(points.slice(0,-1));setSelected(Math.max(0,points.length-2));}}>撤销一点</button><button disabled={!points.length} onClick={()=>{setPoints([]);setSelected(0)}}>重新描绘</button></div></aside></div>
    <footer><span>PDF 共 {pageCount} 页；双面模板只允许选择奇数页或偶数页插图。</span><button onClick={onClose}>取消</button><button className="save-region" disabled={points.length<3||!name.trim()||(draftDuplex&&draftPageMode==='all')} onClick={()=>onSave(regions,name.trim(),draftHasCover,draftPageMode,draftDuplex,draftRotateCover,draftRotateInner)}>保存模板配置</button></footer>
  </section></div>;
}
